services:
  postgres:
    image: postgres:15
    container_name: modchecker_db
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  bot:
    build: .
    container_name: modchecker_bot
    env_file:
      - ./.env
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
